version: 0.2

phases:
  install:
    commands:
      - npm i npm@latest -g
      - npm install -g yarn
      - pip install --upgrade pip
      - pip install --upgrade awscli
  pre_build:
    commands:
      - echo Pre_build Phase
      - yarn install --ignore-engines
  build:
    commands:
      - echo Build Phase
      - yarn run build
  post_build:
    commands:
      - echo PostBuild Phase
      - aws s3 sync ./dist ${S3_BUCKET}
      - aws cloudfront create-invalidation --distribution-id ${DISTRIBUTION_ID} --paths '/*'
