/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('./src/components/field/AutoComplete.vue')['default']
    Base: typeof import('./src/components/field/Base.vue')['default']
    BaseItem: typeof import('./src/components/list/BaseItem.vue')['default']
    Basic: typeof import('./src/components/overlay/Basic.vue')['default']
    Currency: typeof import('./src/components/field/Currency.vue')['default']
    Date: typeof import('./src/components/field/Date.vue')['default']
    DateTime: typeof import('./src/components/field/DateTime.vue')['default']
    Delete: typeof import('./src/components/modal/Delete.vue')['default']
    Header: typeof import('./src/components/breadcrumbs/Header.vue')['default']
    LoadingItem: typeof import('./src/components/list/LoadingItem.vue')['default']
    Main: typeof import('./src/components/base/list/Main.vue')['default']
    Number: typeof import('./src/components/field/Number.vue')['default']
    NutriBar: typeof import('./src/components/score/NutriBar.vue')['default']
    NutriSlim: typeof import('./src/components/score/NutriSlim.vue')['default']
    PageWrapper: typeof import('./src/components/base/PageWrapper.vue')['default']
    Primary: typeof import('./src/components/button/Primary.vue')['default']
    Radio: typeof import('./src/components/field/Radio.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/field/Select.vue')['default']
    SimpleList: typeof import('./src/components/list/SimpleList.vue')['default']
    StepFrame: typeof import('./src/components/stepper/StepFrame.vue')['default']
    StepperNav: typeof import('./src/components/stepper/StepperNav.vue')['default']
    TabGroup: typeof import('./src/components/menu/TabGroup.vue')['default']
    TabWrapper: typeof import('./src/components/base/TabWrapper.vue')['default']
    Text: typeof import('./src/components/field/Text.vue')['default']
    TextArea: typeof import('./src/components/field/TextArea.vue')['default']
    Time: typeof import('./src/components/field/Time.vue')['default']
    Toggle: typeof import('./src/components/field/Toggle.vue')['default']
    ToolDropdown: typeof import('./src/components/base/list/components/ToolDropdown.vue')['default']
  }
}
